{
  "formatVersion": "1.1",
  "component": {
    "url": "../../desktop/1.1.0/desktop-1.1.0.module",
    "group": "org.jetbrains.compose.desktop",
    "module": "desktop",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "desktop-jvm-1.1.0.jar",
          "url": "desktop-jvm-1.1.0.jar",
          "size": 7688,
          "sha512": "cf24b3f1bceaa511548e72d3feb44643c3bbc862f27ab9278ba18d9312f97d2c78beb7e796f472fc0eab1e628301429579341d6afe920d6ee1e1fdb0ce63f29e",
          "sha256": "c898b5cb62c45c06a22c3153b7511a9037e190709ccdcd50d50f3d000732da37",
          "sha1": "5ee1b0cb95662b9ec8e19c2d7f94b38673fdbe14",
          "md5": "a0fb36d5ce8399d2836e3e8fb6f5737e"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "desktop-jvm-1.1.0.jar",
          "url": "desktop-jvm-1.1.0.jar",
          "size": 7688,
          "sha512": "cf24b3f1bceaa511548e72d3feb44643c3bbc862f27ab9278ba18d9312f97d2c78beb7e796f472fc0eab1e628301429579341d6afe920d6ee1e1fdb0ce63f29e",
          "sha256": "c898b5cb62c45c06a22c3153b7511a9037e190709ccdcd50d50f3d000732da37",
          "sha1": "5ee1b0cb95662b9ec8e19c2d7f94b38673fdbe14",
          "md5": "a0fb36d5ce8399d2836e3e8fb6f5737e"
        }
      ]
    }
  ]
}
