{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui/1.1.0/ui-1.1.0.module",
    "group": "org.jetbrains.compose.ui",
    "module": "ui",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-swing",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "ui-desktop-1.1.0.jar",
          "url": "ui-desktop-1.1.0.jar",
          "size": 1940749,
          "sha512": "4e9c8894d332f9b9f29fcf71b0d9b62b85a6e1e9f4609a699c277d5936b03694f699711cd9ef106d900aa8afe7160c10d312b6786d1224ee186c8bf9c2b631d6",
          "sha256": "acb63336a647a3651112ef2ea0dd8edd3bd9eceb4236279389424b4f59301240",
          "sha1": "4884062666a55d239ce40c5c85202fea17638e0c",
          "md5": "6c8c49589233496c16f92f8b10f5a43f"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-swing",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.7.12"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "ui-desktop-1.1.0.jar",
          "url": "ui-desktop-1.1.0.jar",
          "size": 1940749,
          "sha512": "4e9c8894d332f9b9f29fcf71b0d9b62b85a6e1e9f4609a699c277d5936b03694f699711cd9ef106d900aa8afe7160c10d312b6786d1224ee186c8bf9c2b631d6",
          "sha256": "acb63336a647a3651112ef2ea0dd8edd3bd9eceb4236279389424b4f59301240",
          "sha1": "4884062666a55d239ce40c5c85202fea17638e0c",
          "md5": "6c8c49589233496c16f92f8b10f5a43f"
        }
      ]
    }
  ]
}
