{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.compose.animation",
    "module": "animation",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "animation-metadata-1.1.0.jar",
          "url": "animation-1.1.0.jar",
          "size": 25357,
          "sha512": "722c9b28221227c6912194a074aad63ea0b23a7f8079661a6564d3b6d61160b85e984275f349bb0b5c955b53af353c4e4d6c253205d8932bfa34ded0adb82ed2",
          "sha256": "531acf0cd34a3e3a2c01466fd543a9cbe7dab9a6659486212a782e931a183ea3",
          "sha1": "c8b4b200a3fa6d24f8568f83e4cb61ca5d89ad67",
          "md5": "6e637cc655040420112fe90e8d5885af"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ]
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../animation-desktop/1.1.0/animation-desktop-1.1.0.module",
        "group": "org.jetbrains.compose.animation",
        "module": "animation-desktop",
        "version": "1.1.0"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../animation-desktop/1.1.0/animation-desktop-1.1.0.module",
        "group": "org.jetbrains.compose.animation",
        "module": "animation-desktop",
        "version": "1.1.0"
      }
    }
  ]
}
