{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.skiko",
    "module": "skiko",
    "version": "0.7.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "skiko-metadata-0.7.12-all.jar",
          "url": "skiko-0.7.12-all.jar",
          "size": 107475,
          "sha512": "b8a8d3c024ebd3e79d21d883444b302940b79b8b40c5ce40672a32111d3390dfed484b5085557eb2161c73558e9d0ca8260b1aa91a54fe0282233bb611a7e585",
          "sha256": "890796d1a036645377c36c3354a465a81e5d56cafaabb1b15fc1d71c79473fef",
          "sha1": "9ad09bc70a1af779b8e5428f1a7b6cf98ed3f10e",
          "md5": "e0702d4d0b6c4efcff0daa19756409ce"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "skiko-0.7.12.jar",
          "url": "skiko-0.7.12.jar",
          "size": 184936,
          "sha512": "c7b1fec038aa0d7f185d956952b5c1a16619a8e49343c67788293ed58dd5b6ef15e3b4d94560da07307b2fc21fe629b3b680b49830d8c426da385ed297e14500",
          "sha256": "5e8baef6886318c20ef0145c6fdfb5883894a7afe4a16f709966d381af5afb56",
          "sha1": "e268c4f28a849c6eb59e3a01bfb858a8da0096bd",
          "md5": "3d5727b516545d61d66713fc4fc15c7a"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm",
        "ui": "android"
      },
      "available-at": {
        "url": "../../skiko-android/0.7.12/skiko-android-0.7.12.module",
        "group": "org.jetbrains.skiko",
        "module": "skiko-android",
        "version": "0.7.12"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm",
        "ui": "android"
      },
      "available-at": {
        "url": "../../skiko-android/0.7.12/skiko-android-0.7.12.module",
        "group": "org.jetbrains.skiko",
        "module": "skiko-android",
        "version": "0.7.12"
      }
    },
    {
      "name": "awtApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../skiko-awt/0.7.12/skiko-awt-0.7.12.module",
        "group": "org.jetbrains.skiko",
        "module": "skiko-awt",
        "version": "0.7.12"
      }
    },
    {
      "name": "awtRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../skiko-awt/0.7.12/skiko-awt-0.7.12.module",
        "group": "org.jetbrains.skiko",
        "module": "skiko-awt",
        "version": "0.7.12"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../skiko-iosarm64/0.7.12/skiko-iosarm64-0.7.12.module",
        "group": "org.jetbrains.skiko",
        "module": "skiko-iosarm64",
        "version": "0.7.12"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../skiko-iosarm64/0.7.12/skiko-iosarm64-0.7.12.module",
        "group": "org.jetbrains.skiko",
        "module": "skiko-iosarm64",
        "version": "0.7.12"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../skiko-iosx64/0.7.12/skiko-iosx64-0.7.12.module",
        "group": "org.jetbrains.skiko",
        "module": "skiko-iosx64",
        "version": "0.7.12"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../skiko-iosx64/0.7.12/skiko-iosx64-0.7.12.module",
        "group": "org.jetbrains.skiko",
        "module": "skiko-iosx64",
        "version": "0.7.12"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../skiko-js/0.7.12/skiko-js-0.7.12.module",
        "group": "org.jetbrains.skiko",
        "module": "skiko-js",
        "version": "0.7.12"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../skiko-js/0.7.12/skiko-js-0.7.12.module",
        "group": "org.jetbrains.skiko",
        "module": "skiko-js",
        "version": "0.7.12"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../skiko-linuxx64/0.7.12/skiko-linuxx64-0.7.12.module",
        "group": "org.jetbrains.skiko",
        "module": "skiko-linuxx64",
        "version": "0.7.12"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../skiko-macosarm64/0.7.12/skiko-macosarm64-0.7.12.module",
        "group": "org.jetbrains.skiko",
        "module": "skiko-macosarm64",
        "version": "0.7.12"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../skiko-macosarm64/0.7.12/skiko-macosarm64-0.7.12.module",
        "group": "org.jetbrains.skiko",
        "module": "skiko-macosarm64",
        "version": "0.7.12"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../skiko-macosx64/0.7.12/skiko-macosx64-0.7.12.module",
        "group": "org.jetbrains.skiko",
        "module": "skiko-macosx64",
        "version": "0.7.12"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../skiko-macosx64/0.7.12/skiko-macosx64-0.7.12.module",
        "group": "org.jetbrains.skiko",
        "module": "skiko-macosx64",
        "version": "0.7.12"
      }
    }
  ]
}
